CREATE SCHEMA "Schema"
GO

CREATE TABLE "Schema"."ADRES" (
		"ULICA" CHAR(20) NULL,
		"NR_DOMU" INT NULL,
		"NR_MIESZKANIA" INT NULL,
		"KOD_POCZTOWY" CHAR(20) NULL,
		"MIASTO" CHAR(20) NULL
	)
GO

CREATE TABLE "Schema"."BADANIE" (
		"DATA_BADANIA" DATETIME NULL,
		"RODZAJ" CHAR(50) NULL,
		"WYNIK" IMAGE NULL,
		"BADANIE_ID" INT NOT NULL IDENTITY (1,1),
		"KARTA_PACJENTA_ID" INT NULL,
		"LEKARZ_ZLECAJACY" INT NULL
	)
GO

CREATE TABLE "Schema"."GABINET" (
		"NR" CHAR(10) NULL,
		"BUDYNEK" CHAR(10) NULL,
		"RODZAJ" CHAR(30) NULL,
		"GABINET_ID" INT NOT NULL IDENTITY (1,1),
		"LEKARZ_ODPOWIEDZIALNY" INT NULL
	)
GO

CREATE TABLE "Schema"."KARTA_PACJENTA" (
		"NUMER_KARTY" CHAR(20) NULL,
		"DATA_ZALOZENIA" DATE NULL,
		"KARTA_PACJENTA_ID" INT NOT NULL IDENTITY (1,1),
		"WLASCICIEL" INT NOT NULL,
		"PROWADZACY" INT NULL
	)
GO

CREATE TABLE "Schema"."KONSULTACJA_ONLINE" (
		"DATA" DATETIME NULL,
		"OPIS" CHAR(200) NULL,
		"KONSULTACJA_ONLINE_ID" INT NOT NULL IDENTITY (1,1),
		"PACJENT_ID" INT NULL,
		"KONSULTANT_ID" INT NULL
	)
GO

CREATE TABLE "Schema"."KONSULTANT" (
		"GODZINY_KONSULTACJI" CHAR(10) NULL,
		"IMIE" CHAR(20) NULL,
		"NAZWISKO" CHAR(20) NULL,
		"SPECJALIZACJA" CHAR(10) NULL,
		"NR_LICENCJI" CHAR(20) NULL,
		"DATA_URODZENIA" DATE NULL,
		"KONSULTANT_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

CREATE TABLE "Schema"."LEKARZ" (
		"IMIE" CHAR(20) NULL,
		"NAZWISKO" CHAR(20) NULL,
		"SPECJALIZACJA" CHAR(20) NULL,
		"DATA_URODZENIA" DATE NULL,
		"NR_LICENCJI" CHAR(20) NULL,
		"LEKARZ_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

CREATE TABLE "Schema"."OPINIA" (
		"NUMER_OPINII" INT NULL,
		"TRESC" CHAR(200) NULL,
		"OCENA" INT NULL,
		"OPINIA_ID" INT NOT NULL IDENTITY (1,1),
		"LEKARZ_ID" INT NULL,
		"PACJENT_ID" INT NULL
	)
GO

CREATE TABLE "Schema"."PACJENT" (
		"IMIE" CHAR(20) NULL,
		"NAZWISKO" CHAR(20) NULL,
		"PESEL" CHAR(11) NULL,
		"DATA_URODZENIA" DATE NULL,
		"MIEJSCE_URODZENIA" CHAR(20) NULL,
		"ULICA_ZAMIESZKANIA" CHAR(20) NULL,
		"MIEJSCOWOSC" CHAR(20) NULL,
		"KOD_POCZTOWY" CHAR(10) NULL,
		"ADRES_E-MAIL" CHAR(30) NULL,
		"NR_TELEFONU" CHAR(15) NULL,
		"PACJENT_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

CREATE TABLE "Schema"."POWIADOMIENIE" (
		"NUMER_POWIADOMIENIA" INT NULL,
		"TRESC" CHAR(500) NULL,
		"POWIADOMIENIE_ID" INT NOT NULL IDENTITY (1,1),
		"PACJENT_ID" INT NULL,
		"LEKARZ_ID" INT NULL,
		"STATUS" CHAR(20) NULL
	)
GO

CREATE TABLE "Schema"."TERMINARZ" (
		"DATA" DATE NULL,
		"GODZINA" TIME NULL,
		"TERMINARZ_ID" INT NOT NULL IDENTITY (1,1),
		"LEKARZ_ID" INT NULL
	)
GO

CREATE TABLE "Schema"."WIZYTA_DOMOWA" (
		"WIZYTA_DOMOWA_ID" INT NOT NULL IDENTITY (1,1),
		"PACJENT_ID" INT NULL,
		"LEKARZ_ID" INT NULL,
		"ULICA" CHAR(30) NULL,
		"KOD_POCZTOWY" CHAR(10) NULL,
		"NR_DOMU" CHAR(5) NULL,
		"MIEJSCOWOSC" CHAR(20) NULL
	)
GO

CREATE TABLE "Schema"."WIZYTA_DOMOWA_X_TERMINARZ" (
		"WIZYTA_DOMOWA_ID" INT NOT NULL,
		"TERMINARZ_ID" INT NOT NULL
	)
GO

CREATE TABLE "Schema"."WIZYTA_KONSULTACYJNA" (
		"WIZYTA_KONSULTACYJNA_ID" INT NOT NULL IDENTITY (1,1),
		"PACJENT_ID" INT NULL,
		"GABINET_ID" INT NULL,
		"LEKARZ_ID" INT NULL,
		"CEL" CHAR(200) NULL,
		"DODATKOWE_UWAGI" CHAR(200) NULL
	)
GO

CREATE TABLE "Schema"."WIZYTA_KONSULTACYJNA_X_TERMINARZ" (
		"WIZYTA_KONSULTACYJNA_ID" INT NOT NULL,
		"TERMINARZ_ID" INT NOT NULL
	)
GO

ALTER TABLE "Schema"."BADANIE" ADD CONSTRAINT "BADANIE_PK" PRIMARY KEY
	("BADANIE_ID")
GO

ALTER TABLE "Schema"."GABINET" ADD CONSTRAINT "GABINET_PK" PRIMARY KEY
	("GABINET_ID")
GO

ALTER TABLE "Schema"."KARTA_PACJENTA" ADD CONSTRAINT "KARTA_PACJENTA_PK" PRIMARY KEY
	("KARTA_PACJENTA_ID")
GO

ALTER TABLE "Schema"."KONSULTACJA_ONLINE" ADD CONSTRAINT "KONSULTACJA_ONLINE_PK" PRIMARY KEY
	("KONSULTACJA_ONLINE_ID")
GO

ALTER TABLE "Schema"."KONSULTANT" ADD CONSTRAINT "KONSULTANT_PK" PRIMARY KEY
	("KONSULTANT_ID")
GO

ALTER TABLE "Schema"."LEKARZ" ADD CONSTRAINT "LEKARZ_PK" PRIMARY KEY
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."OPINIA" ADD CONSTRAINT "OPINIA_PK" PRIMARY KEY
	("OPINIA_ID")
GO

ALTER TABLE "Schema"."PACJENT" ADD CONSTRAINT "PACJENT_PK" PRIMARY KEY
	("PACJENT_ID")
GO

ALTER TABLE "Schema"."POWIADOMIENIE" ADD CONSTRAINT "POWIADOMIENIE_PK" PRIMARY KEY
	("POWIADOMIENIE_ID")
GO

ALTER TABLE "Schema"."TERMINARZ" ADD CONSTRAINT "TERMINARZ_PK" PRIMARY KEY
	("TERMINARZ_ID")
GO

ALTER TABLE "Schema"."WIZYTA_DOMOWA" ADD CONSTRAINT "WIZYTA_DOMOWA_PK" PRIMARY KEY
	("WIZYTA_DOMOWA_ID")
GO

ALTER TABLE "Schema"."WIZYTA_DOMOWA_X_TERMINARZ" ADD CONSTRAINT "WIZYTA_DOMOWA_X_TERMINARZ_PK" PRIMARY KEY
	("WIZYTA_DOMOWA_ID",
	 "TERMINARZ_ID")
GO

ALTER TABLE "Schema"."WIZYTA_KONSULTACYJNA" ADD CONSTRAINT "WIZYTA_KONSULTACYJNA_PK" PRIMARY KEY
	("WIZYTA_KONSULTACYJNA_ID")
GO

ALTER TABLE "Schema"."WIZYTA_KONSULTACYJNA_X_TERMINARZ" ADD CONSTRAINT "WIZYTA_KONSULTACYJNA_X_TERMINARZ_PK" PRIMARY KEY
	("WIZYTA_KONSULTACYJNA_ID",
	 "TERMINARZ_ID")
GO

ALTER TABLE "Schema"."BADANIE" ADD CONSTRAINT "BADANIE_KARTA_PACJENTA_FK" FOREIGN KEY
	("KARTA_PACJENTA_ID")
	REFERENCES "Schema"."KARTA_PACJENTA"
	("KARTA_PACJENTA_ID")
GO

ALTER TABLE "Schema"."BADANIE" ADD CONSTRAINT "BADANIE_LEKARZ_FK" FOREIGN KEY
	("LEKARZ_ZLECAJACY")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."GABINET" ADD CONSTRAINT "GABINET_LEKARZ_FK" FOREIGN KEY
	("LEKARZ_ODPOWIEDZIALNY")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."KARTA_PACJENTA" ADD CONSTRAINT "KARTA_PACJENTA_LEKARZ_FK" FOREIGN KEY
	("PROWADZACY")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."KARTA_PACJENTA" ADD CONSTRAINT "KARTA_PACJENTA_PACJENT_FK" FOREIGN KEY
	("WLASCICIEL")
	REFERENCES "Schema"."PACJENT"
	("PACJENT_ID")
GO

ALTER TABLE "Schema"."KONSULTACJA_ONLINE" ADD CONSTRAINT "KONSULTACJA_ONLINE_KONSULTANT_FK" FOREIGN KEY
	("KONSULTANT_ID")
	REFERENCES "Schema"."KONSULTANT"
	("KONSULTANT_ID")
GO

ALTER TABLE "Schema"."KONSULTACJA_ONLINE" ADD CONSTRAINT "KONSULTACJA_ONLINE_PACJENT_FK" FOREIGN KEY
	("PACJENT_ID")
	REFERENCES "Schema"."PACJENT"
	("PACJENT_ID")
GO

ALTER TABLE "Schema"."OPINIA" ADD CONSTRAINT "OPINIA_LEKARZ_FK" FOREIGN KEY
	("LEKARZ_ID")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."OPINIA" ADD CONSTRAINT "OPINIA_PACJENT_FK" FOREIGN KEY
	("PACJENT_ID")
	REFERENCES "Schema"."PACJENT"
	("PACJENT_ID")
GO

ALTER TABLE "Schema"."POWIADOMIENIE" ADD CONSTRAINT "POWIADOMIENIE_LEKARZ_FK" FOREIGN KEY
	("LEKARZ_ID")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."POWIADOMIENIE" ADD CONSTRAINT "POWIADOMIENIE_PACJENT_FK" FOREIGN KEY
	("PACJENT_ID")
	REFERENCES "Schema"."PACJENT"
	("PACJENT_ID")
GO

ALTER TABLE "Schema"."TERMINARZ" ADD CONSTRAINT "TERMINARZ_LEKARZ_FK" FOREIGN KEY
	("LEKARZ_ID")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."WIZYTA_DOMOWA" ADD CONSTRAINT "WIZYTA_DOMOWA_LEKARZ_FK" FOREIGN KEY
	("LEKARZ_ID")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."WIZYTA_DOMOWA" ADD CONSTRAINT "WIZYTA_DOMOWA_PACJENT_FK" FOREIGN KEY
	("PACJENT_ID")
	REFERENCES "Schema"."PACJENT"
	("PACJENT_ID")
GO

ALTER TABLE "Schema"."WIZYTA_DOMOWA_X_TERMINARZ" ADD CONSTRAINT "WIZYTA DOMOWA_TERMINARZ_FK" FOREIGN KEY
	("WIZYTA_DOMOWA_ID")
	REFERENCES "Schema"."WIZYTA_DOMOWA"
	("WIZYTA_DOMOWA_ID")
GO

ALTER TABLE "Schema"."WIZYTA_DOMOWA_X_TERMINARZ" ADD CONSTRAINT "WIZYTA DOMOWA_TERMINARZ_FK1" FOREIGN KEY
	("TERMINARZ_ID")
	REFERENCES "Schema"."TERMINARZ"
	("TERMINARZ_ID")
GO

ALTER TABLE "Schema"."WIZYTA_KONSULTACYJNA" ADD CONSTRAINT "WIZYTA_KONSULTACYJNA_GABINET_FK" FOREIGN KEY
	("GABINET_ID")
	REFERENCES "Schema"."GABINET"
	("GABINET_ID")
GO

ALTER TABLE "Schema"."WIZYTA_KONSULTACYJNA" ADD CONSTRAINT "WIZYTA_KONSULTACYJNA_LEKARZ_FK" FOREIGN KEY
	("LEKARZ_ID")
	REFERENCES "Schema"."LEKARZ"
	("LEKARZ_ID")
GO

ALTER TABLE "Schema"."WIZYTA_KONSULTACYJNA" ADD CONSTRAINT "WIZYTA_KONSULTACYJNA_PACJENT_FK" FOREIGN KEY
	("PACJENT_ID")
	REFERENCES "Schema"."PACJENT"
	("PACJENT_ID")
GO

ALTER TABLE "Schema"."WIZYTA_KONSULTACYJNA_X_TERMINARZ" ADD CONSTRAINT "WIZYTA KONSULTACYJNA_TERMINARZ_FK" FOREIGN KEY
	("WIZYTA_KONSULTACYJNA_ID")
	REFERENCES "Schema"."WIZYTA_KONSULTACYJNA"
	("WIZYTA_KONSULTACYJNA_ID")
GO

ALTER TABLE "Schema"."WIZYTA_KONSULTACYJNA_X_TERMINARZ" ADD CONSTRAINT "WIZYTA KONSULTACYJNA_TERMINARZ_FK1" FOREIGN KEY
	("TERMINARZ_ID")
	REFERENCES "Schema"."TERMINARZ"
	("TERMINARZ_ID")
GO

